version: '3.7'
services:
  db:
    container_name: simpleshop-db
    image: postgres:10.13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "7001:5432"
  redis:
    image: redis:6.0.2-alpine
    ports:
      - "7002:6379"
  web:
    container_name: simpleshop-web
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - './:/api'
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  data:
